[project]
name = "ai-engineer-100days"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "guna", email = "kattaguna06@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.15.0",
    "datasets>=5.0.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[project.scripts]
ai-engineer-100days = "ai_engineer_100days:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
